name: Binder Cache Push
on: 
  push:
    paths-ignore:
      - 'binder/**'
    branches: 
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Create-And-Push-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: ${{ env.REGISTRY }}
        IMAGE_NAME: "jij-inc/playground"
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
