name: Binder Cache Push
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - 'binder/**'
    branches: 
      - main

concurrency:
      group: Binder-Cache-Push
      cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jij-inc/playground

jobs:
  Create-And-Push-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: ${{ env.REGISTRY }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
