name: Binder
on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Binder Cache Push]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        IMAGE_NAME: "jij-inc/playground"
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
